mappings:
  SearchEngineProviderMYSQLFullText: Sunnysideup\SearchSimpleSmart\Api\SearchEngineProviderMYSQLFullText
  SearchEngineRecordClick: Sunnysideup\SearchSimpleSmart\Control\SearchEngineRecordClick
  SearchEngineSortByRelevance: Sunnysideup\SearchSimpleSmart\Sorters\SearchEngineSortByRelevance
  SearchEngineSortByDate: Sunnysideup\SearchSimpleSmart\Sorters\SearchEngineSortByDate
  SearchEngineFilterForDescriptor: Sunnysideup\SearchSimpleSmart\Abstractions\SearchEngineFilterForDescriptor
  SearchEngineSearchEngineProvider: Sunnysideup\SearchSimpleSmart\Abstractions\SearchEngineSearchEngineProvider
  SearchEngineCoreMachineProvider: Sunnysideup\SearchSimpleSmart\Abstractions\SearchEngineCoreMachineProvider
  SearchEngineSortByDescriptor: Sunnysideup\SearchSimpleSmart\Abstractions\SearchEngineSortByDescriptor
  SearchEngineMakeSearchableInterface: Sunnysideup\SearchSimpleSmart\Abstractions\SearchEngineMakeSearchableInterface
  SearchEngineSearchHistoryFormField: Sunnysideup\SearchSimpleSmart\Forms\Fields\SearchEngineSearchHistoryFormField
  SearchEngineBasicForm: Sunnysideup\SearchSimpleSmart\Forms\SearchEngineBasicForm
  SearchEngineAdmin: Sunnysideup\SearchSimpleSmart\Admin\SearchEngineAdmin
  SearchEngineCoreSearchMachine: Sunnysideup\SearchSimpleSmart\Core\SearchEngineCoreSearchMachine
  SearchEngineFilterForRecent: Sunnysideup\SearchSimpleSmart\Filters\SearchEngineFilterForRecent
  SearchEngineFilterForClassName: Sunnysideup\SearchSimpleSmart\Filters\SearchEngineFilterForClassName
  SearchEngineKeywordFindAndRemove: Sunnysideup\SearchSimpleSmart\Model\SearchEngineKeywordFindAndRemove
  SearchEnginePunctuationFindAndRemove: Sunnysideup\SearchSimpleSmart\Model\SearchEnginePunctuationFindAndRemove
  SearchEngineSearchRecordHistory: Sunnysideup\SearchSimpleSmart\Model\SearchEngineSearchRecordHistory
  SearchEngineKeywordFindAndReplace: Sunnysideup\SearchSimpleSmart\Model\SearchEngineKeywordFindAndReplace
  SearchEngineDataObjectToBeIndexed: Sunnysideup\SearchSimpleSmart\Model\SearchEngineDataObjectToBeIndexed
  SearchEngineFullContent: Sunnysideup\SearchSimpleSmart\Model\SearchEngineFullContent
  SearchEngineDataObject: Sunnysideup\SearchSimpleSmart\Model\SearchEngineDataObject
  SearchEngineKeyword: Sunnysideup\SearchSimpleSmart\Model\SearchEngineKeyword
  SearchEngineAdvancedSettings: Sunnysideup\SearchSimpleSmart\Model\SearchEngineAdvancedSettings
  SearchEngineSearchRecord: Sunnysideup\SearchSimpleSmart\Model\SearchEngineSearchRecord
  SearchEngineSiteConfigExtension: Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineSiteConfigExtension
  SearchEngineMakeSearchable: Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineMakeSearchable
  SearchEngineContentControllerExtension: Sunnysideup\SearchSimpleSmart\Extensions\SearchEngineContentControllerExtension
  SearchEngineIndexAll: Sunnysideup\SearchSimpleSmart\Tasks\SearchEngineIndexAll
  SearchEngineCreateKeywordJS: Sunnysideup\SearchSimpleSmart\Tasks\SearchEngineCreateKeywordJS
  SearchEngineUpdateSearchIndex: Sunnysideup\SearchSimpleSmart\Tasks\SearchEngineUpdateSearchIndex
  SearchEngineRemoveAll: Sunnysideup\SearchSimpleSmart\Tasks\SearchEngineRemoveAll
